version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spring_one
    ports:
      - "3306:3306"

  springbootapp:
    build: .
    container_name: springbootapp
    ports:
      - "8085:8085"
    depends_on:
      - mysql
